"""empty message

Revision ID: 1e7821f33735
Revises: 52db1dc47d09
Create Date: 2022-12-11 10:09:26.831409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e7821f33735'
down_revision = '52db1dc47d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syuser', sa.Column('id', sa.String(length=36), nullable=False))
    op.alter_column('syuser', 'userName',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_syuser_userName'), 'syuser', ['userName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syuser_userName'), table_name='syuser')
    op.alter_column('syuser', 'userName',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('syuser', 'id')
    # ### end Alembic commands ###
